// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3x6xd3cbvyjL6l_I97hJ6JeHbMHUgerU',
    appId: '1:340503092261:web:6f0e1387eb9471fb52b3cc',
    messagingSenderId: '340503092261',
    projectId: 'rdp-todolist3-3ffbb',
    authDomain: 'rdp-todolist3-3ffbb.firebaseapp.com',
    storageBucket: 'rdp-todolist3-3ffbb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDacfHOjg0eycE5NbkVsKqu0AvRfILqgM0',
    appId: '1:340503092261:android:ad6f5af32633bf6f52b3cc',
    messagingSenderId: '340503092261',
    projectId: 'rdp-todolist3-3ffbb',
    storageBucket: 'rdp-todolist3-3ffbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJEiVlwXnFT0LSt10aN0lgiS6DpK_jtKM',
    appId: '1:340503092261:ios:ea555cc928a97b9352b3cc',
    messagingSenderId: '340503092261',
    projectId: 'rdp-todolist3-3ffbb',
    storageBucket: 'rdp-todolist3-3ffbb.appspot.com',
    iosBundleId: 'com.example.rdpTodolist3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJEiVlwXnFT0LSt10aN0lgiS6DpK_jtKM',
    appId: '1:340503092261:ios:ea555cc928a97b9352b3cc',
    messagingSenderId: '340503092261',
    projectId: 'rdp-todolist3-3ffbb',
    storageBucket: 'rdp-todolist3-3ffbb.appspot.com',
    iosBundleId: 'com.example.rdpTodolist3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3x6xd3cbvyjL6l_I97hJ6JeHbMHUgerU',
    appId: '1:340503092261:web:908217069859f17f52b3cc',
    messagingSenderId: '340503092261',
    projectId: 'rdp-todolist3-3ffbb',
    authDomain: 'rdp-todolist3-3ffbb.firebaseapp.com',
    storageBucket: 'rdp-todolist3-3ffbb.appspot.com',
  );
}
